global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'bank-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8081']
    # basic_auth:
    #   username: "matt@example.com"
    #   password: "secret"
    # tls_config:
    #   insecure_skip_verify: true